messenger/ChatApp/urls.py
from django.urls import path

from . import views


app_name = 'Chat'
urlpatterns = [
    path('chat_choice/', views.chat_choice, name='chat_choice'),
    path('distribution/', views.distribution, name='distribution'),
    path('save_distribution/', views.save_distribution, name='save_distribution'),
    path('delete_room/<str:room_name>', views.delete_room, name='delete_room'),
    path('<str:room_name>/', views.room, name='room'),
]

messenger/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls')),
    path('chat/', include('ChatApp.urls')),
    path('accounts/', include(('accounts.urls'))),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/ChatApp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone


class Room(models.Model):
    name = models.TextField(max_length=50)
    user_simple = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name="User")
    user_admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name="Admin")

    def __str__(self):
        return self.name


class Message(models.Model):
    content = models.TextField(max_length=500)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    send_date = models.DateTimeField(default=timezone.now())
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='message')

messenger/ChatApp/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

from .models import Room, Message

from django.http import HttpResponseRedirect
from dataclasses import dataclass
from django.db.models.query import QuerySet

import time
import json


@dataclass
class DialogData:
    room_name: str
    last_message_content: str
    last_message_send_date: str
    user: QuerySet


@login_required
def chat_choice(request):
    context = {
        'page': 2,
        'page_title': 'Диалоги',
    }
    room_name_and_user = list()
    unique_rooms = list()
    if request.user.is_superuser:
        rooms_qs = Room.objects.exclude(name=request.user.username).order_by('-message__send_date')
        for i, room in enumerate(rooms_qs):
            try:
                msg_content = room.message.last().content
                msg_date = room.message.last().send_date
            except:
                msg_content = ''
                msg_date = ''
            room_name_and_user.append(
                DialogData(
                    room_name=room.name,
                    last_message_content=msg_content,
                    last_message_send_date=msg_date,
                    user=room.user_simple
                )
            )

            if room_name_and_user[i] not in unique_rooms:
                unique_rooms.append(room_name_and_user[i])
    else:
        try:
            room = Room.objects.get(name=request.user.username)
        except:
            return render(request, 'Chat/chat_choice.html', context)
        try:
            msg_content = room.message.last().content
            msg_date = room.message.last().send_date
        except:
            msg_content = ''
            msg_date = ''
        unique_rooms.append(
            DialogData(
                room_name=room.name,
                last_message_content=msg_content,
                last_message_send_date=msg_date,
                user=room.user_admin
            )
        )

    context['room_name_and_user'] = unique_rooms
    return render(request, 'Chat/chat_choice.html', context)


@permission_required('polls.can_vote')
def distribution(request):
    if request.user.is_superuser:
        users = User.objects.exclude(is_superuser=True)
    else:
        users = User.objects.filter(username=request.user)

    context = {
        'page': 2,
        'page_title': 'Групповая рассылка',
        'users': users,
    }
    return render(request, 'Chat/distribution.html', context)


@permission_required('polls.can_vote')
def save_distribution(request):
    try:
        content = request.POST['content']
    except:
        content = ''
    users = request.POST.getlist('search')
    user_admin = User.objects.get(is_superuser=True)
    for user in users:
        author = User.objects.get(username=user_admin)
        try:
            current_room = Room.objects.get(name=user)
        except Room.DoesNotExist:
            user = User.objects.get(username=user)
            Room.objects.create(name=user.username, user_simple=user,
                                user_admin=author)
            current_room = Room.objects.get(name=user)
        Message.objects.create(content=content, author=author, room=current_room)
    return HttpResponseRedirect(reverse('Chat:chat_choice'))


@login_required
def room(request, room_name):
    # Get user and user_admin
    try:
        user = User.objects.get(username=room_name)
        user_admin = User.objects.get(is_superuser=True)
    except User.DoesNotExist:
        return False
    # Get current_room or create
    try:
        current_room = Room.objects.get(name=room_name)
    except Room.DoesNotExist:
        Room.objects.create(name=room_name, user_simple=user,
                            user_admin=user_admin)
        current_room = Room.objects.get(name=room_name)
    try:
        messages = current_room.message.all()
    except:
        messages = None

    if request.user == user_admin:
        if user.first_name != '' and user.last_name != '':
            page_title = f'{user.first_name} {user.last_name}'
        else:
            page_title = user.username
    elif request.user == user:
        if user_admin.first_name != '' and user_admin.last_name != '':
            page_title = f'{user_admin.first_name} {user_admin.last_name}'
        else:
            page_title = user_admin.username
    context = {
        'page_title': page_title,
        'messages': messages,
        'current_room_name': mark_safe(json.dumps(current_room.name)),
        'room_name_json': mark_safe(json.dumps(user.username)),
        'current_user': mark_safe(json.dumps(request.user.username)),
        'username': mark_safe(json.dumps(user.username)),
    }

    return render(request, 'Chat/room.html', context)


@permission_required('polls.can_vote')
def delete_room(request, room_name):
    try:
        room = Room.objects.get(name=room_name)
        room.delete()
    except Room.DoesNotExist:
        pass
    return HttpResponseRedirect(reverse('Chat:chat_choice'))

messenger/ChatApp/templates/Chat/chat_choice.html
{% extends 'pwaMessenger/main.html' %}
{% block title %}{{page_title}}{% endblock title %}


{% block search %}
<button class="navbar-toggler toggler-example" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="dark-blue-text">
                <i class="fas fa-bars fa-1x"></i>
            </span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent1">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <select class="mdb-select md-form dropdown-default" searchable="Поиск">
                <option value="" disabled selected>Выберите диалог</option>
                {% for rnau in room_name_and_user %}
                {% if rnau.user.first_name != '' and rnau.user.last_name != ''%}
                <option data-url="{% url 'Chat:room' rnau.room_name %}">
                    {{ rnau.user.first_name }} {{rnau.user.last_name}} ({{rnau.user}})
                </option>
                {% else %}
                <option data-url="{% url 'Chat:room' rnau.room_name %}">{{rnau.user}}</option>
                {% endif %}
                {% endfor %}
            </select>
        </li>
        <li class="nav-item">
            <label class="mdb-main-label">Выберите диалог</label>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item d-flex justify-content-center">
            <a href="{% url 'Chat:distribution' %}" class="mdb-main-label btn btn-default preloader">Групповая
                рассылка</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock search %}
{% block main %}

<div class="col-12 p-0 pt-1">
    {% for rnau in room_name_and_user %}
    <div class="btn-group w-100 dropleft">
        <a href="{% url 'Chat:room' rnau.room_name %}" class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <img src="/media/{{ rnau.user.profile.photo  }}" class="user-photo elegant-color-dark rounded float-left"
                 alt="">
            <div class="w-100">
                {% if rnau.user.first_name != '' and rnau.user.last_name != ''%}
                <p class="text-left h4-responsive text-capitalize ml-2">
                    {{ rnau.user.first_name }} {{ rnau.user.last_name }}
                </p>
                {% else %}

                <p class="text-left h4-responsive text-capitalize ml-2">{{ rnau.user }} </p>
                {% endif %}

                <div class=" ml-2 text-white-50 align-items-center">
                    <div><p class="ellipsis text-capitalize">{{ rnau.last_message_content }}</p></div>
                    <div class="d-flex justify-content-start"><em>{{ rnau.last_message_send_date }}</em></div>
                </div>
            </div>

        </a>
        {% if request.user.is_superuser %}
        <button type="button" class="btn elegant-color dropdown-toggle px-3" data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
        </button>
        <div class="dropdown-menu danger-color">
            <a class="dropdown-item danger-color text-white" href="{% url 'Chat:delete_room' rnau.user %}">Удалить</a>
        </div>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock main %}
{% block scripts %}
<!--  Адаптивный поиск  -->
<script>
    //Переход по результату
    $(".mdb-select").change(function () {
        let option = $(this).find('option:selected');
        if (option.data("url")) {
            window.location.href = option.data("url");
        }
    });


</script>
{% endblock scripts %}

messenger/ChatApp/templates/Chat/distribution.html
{% extends 'pwaMessenger/main.html' %}
{% block nav %}
<li class="nav-item">
    <a class="nav-link p-0" href="{% url 'Chat:chat_choice' %}">
        <svg fill="#FFFFFF" height="36" viewBox="0 0 24 24" width="36" xmlns="http://www.w3.org/2000/svg">
            <path d="M15.41 16.09l-4.58-4.59 4.58-4.59L14 5.5l-6 6 6 6z"/>
            <path d="M0-.5h24v24H0z" fill="none"/>
        </svg>
    </a>
</li>
{% endblock nav %}
{% block title %}{{page_title}}{% endblock title %}

{% block main %}
<div class="col-12 p-3">
    <form action="{% url 'Chat:save_distribution' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control form-control-white" id="formGroupInput" name="content"
                   placeholder="Сообщение для рассылки...">
        </div>
        <select class="mdb-select md-form" multiple searchable="Найти адресатов.." id="SELECT"
                name="search">
            <option value="default" disabled selected>Выберите адресатов</option>
            {% for user in users %}
            <option value="{{user}}">{{user}}</option>
            {% endfor %}
        </select>


        <button class="btn btn-default" type="submit" id="button">Разослать</button>

    </form>
</div>
{% endblock %}

messenger/ChatApp/templates/Chat/room.html
{% extends 'pwaMessenger/main.html' %}
{% block nav %}
<li class="nav-item">
    <a class="nav-link p-0" href="{% url 'Chat:chat_choice' %}">
        <svg fill="#FFFFFF" height="36" viewBox="0 0 24 24" width="36" xmlns="http://www.w3.org/2000/svg">
            <path d="M15.41 16.09l-4.58-4.59 4.58-4.59L14 5.5l-6 6 6 6z"/>
            <path d="M0-.5h24v24H0z" fill="none"/>
        </svg>
    </a>
</li>
{% endblock nav %}
{% block title %}{{page_title}}{% endblock title %}
{% block main %}
<div class="col-12 px-3 pt-1" id="dialog">
    {% for msg in messages %}
    {% if msg.author != request.user %}
    <div class="row">
        <div class="col-12 question justify-content-start mt-3">
            <div class="row">
                <div class="col-10">
                    <div class="bubble bubble-question z-depth-1">
                        <span class="text-break">{{msg.content}}<em
                                class="text-light d-block message-time message-time-start">{{ msg.send_date }}</em></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12 answer justify-content-end mt-3">
            <div class="row justify-content-end">
                <div class="col-10 d-flex justify-content-end">
                    <div class="bubble bubble-answer z-depth-1">
                        <span class="text-break">{{msg.content}}<em
                                class="text-light d-block message-time message-time-end">{{ msg.send_date }}</em></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock main %}
{% block footer %}
<footer class="page-footer font-small elegant-color-dark fixed-bottom">
    <!-- Copyright -->
    <div class="footer-copyright d-flex justify-content-between p-0">
        <div class="container">
            <div class="row text-center">
                <div class="col p-0">
                    <div class="input-group pl-0">
                        <input class="form-control form-control-white border-white" type="text"
                               placeholder="Введите сообщение..."
                               aria-label="send-msg" id="chat-message-input">
                        <div class="input-group-append">
                            <button class="input-group-text elegant-color-dark lighten-1"
                                    id="chat-message-submit">
                                <i class="fas fa-paper-plane text-white"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright -->

</footer>
{% endblock footer %}

{% block scripts %}
<!-- TODO Сделать вывод новых сообзений-->
<script>
    function scrollBot() {
        document.body.scrollTop = document.body.scrollHeight - document.body.clientHeight;
        window.scrollTo(0, document.body.scrollHeight);
    }


    function createDivMessageQuestion(content, date) {

        var div = document.createElement('div');
        div.innerHTML = '<div class="row"><div class="col-12 question justify-content-start mt-3"><div class="row"><div class="col-10"><div class="bubble bubble-question z-depth-1"><span class="text-break">' + content + '<em class="text-light d-block message-time message-time-start">' + date + '</em></span></div></div></div></div></div>';
        return div;
    }

    function createDivMessageAnswer(content, date) {
        var div = document.createElement('div');
        div.innerHTML = '<div class="row"><div class="col-12 answer justify-content-end mt-3"><div class="row justify-content-end"><div class="col-10 d-flex justify-content-end"><div class="bubble bubble-answer z-depth-1"><span class="text-break">' + content + '<em class="text-light d-block message-time message-time-end">' + date + '</em></span></div></div></div></div></div>';
        return div;
    }

    $(document).ready(function () {
        scrollBot();
    })
    let roomName = {{room_name_json}}
    let cur_user = {{current_user}}
    let current_room_name = {{current_room_name}}
    // let messages = {{ messages }}
    //создаем сокет
    let chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');


    // обработка сообщений с бэкенда
    chatSocket.onmessage = function (e) {
        let data = JSON.parse(e.data);

        // let still_online = data['still_online'];
        if (data['message']) {
            let message = data['message'];
            let author = data['author'];
            let date = data['date'];
            if (author == cur_user) {
                var msg = createDivMessageAnswer(message, date);
            } else {
                var msg = createDivMessageQuestion(message, date);
            }
            let main = $('#dialog');
            main.append(msg);
            scrollBot();

        }
    };

    //выхлоп
    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    // document.querySelector('#chat-message-input').focus();
    // document.querySelector('#chat-message-input').onkeyup = function (e) {
    //     if (e.keyCode === 13) {  // enter, return
    //         document.querySelector('#chat-message-submit').click();
    //     }
    // };

    //отправляем на бэкенд сообщение пользователя
    document.querySelector('#chat-message-submit').onclick = function (e) {
        let messageInputDom = document.querySelector('#chat-message-input');
        let message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'author': cur_user,
            'current_room_name': current_room_name,
        }));

        messageInputDom.value = '';


    };

    function delay() {
        return new Promise(resolve => setTimeout(resolve, 5000));
    }

    //Держим сокет открытым
    async function get_page_alive() {
        while (true) {
            await delay();
            await console.log('PAGE_is_ALIVE');
        }
    }

    get_page_alive();
</script>
{% endblock scripts %}