messenger/ChatApp/urls.py
from django.urls import path

from . import views


app_name = 'Chat'
urlpatterns = [
    path('chat_choice/', views.chat_choice, name='chat_choice'),
    path('distribution/', views.distribution, name='distribution'),
    path('save_distribution/', views.save_distribution, name='save_distribution'),
    path('delete_room/<str:room_name>', views.delete_room, name='delete_room'),
    path('<str:room_name>/', views.room, name='room'),
]

messenger/accounts/urls.py
from django.urls import path
from .views import \
    RegisterView, LoginView, logout_view, \
    main, settings, user_management, \
    personal_settings, EditNamesView, delete_user, edit_user_img

#Изменения: убрал contacts из импорта


app_name = 'accounts'
urlpatterns = [
    path('', main, name='main'),
    path('settings/', settings, name='settings'),
    path('user_management/', user_management, name='user_management'),
    # path('edit/', edit, name='edit'),
    # path('contacts/', contacts, name='contacts'),
    path('personal_settings/', personal_settings, name='personal_settings'),
    path('edit_user_names/', EditNamesView.as_view(), name='edit_user_names'),
    path('edit_user_img/', edit_user_img, name='edit_user_img'),

    path('delete_user/<int:user_id>', delete_user, name='delete_user'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

messenger/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls')),
    path('chat/', include('ChatApp.urls')),
    path('accounts/', include(('accounts.urls'))),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True, default='users/default.png')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

messenger/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate
from accounts.tools import tools
from .models import Profile


class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'id': 'loginInput',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'id': 'passwordInput',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'id': 'passwordInput',
    }))

    class Meta:
        model = User
        fields = {'username', 'password'}

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            tools.change_widget_attrs_class_to_invalid(self, 'username')
            user = User.objects.get(username=username)
            raise ValidationError('Имя пользователя занято')
        except User.DoesNotExist:
            tools.change_widget_attrs_class_to_valid(self, 'username')
            return username

    def clean_password(self):
        password = self.cleaned_data['password']
        password2 = self.data['password2']
        if password != password2:
            tools.change_widget_attrs_class_to_invalid(self, 'password')
            tools.change_widget_attrs_class_to_invalid(self, 'password2')
            raise ValidationError('Пароли не совпадают')
        return password


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'id': 'loginInput',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
        'id': 'passwordInput',
    }))

    fields = {'username', 'password'}

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.get(username=username)
            tools.change_widget_attrs_class_to_valid(self, 'username')
        except User.DoesNotExist:
            tools.change_widget_attrs_class_to_invalid(self, 'username')
            raise ValidationError('Пользователя не существует')
        return username

    def clean_password(self):
        username = self.data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is None:
            tools.change_widget_attrs_class_to_invalid(self, 'password')
            raise ValidationError('Пароль не верный')
        return password


class EditUserNames(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off',
    }))

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        return last_name


class EditUserPhoto(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo',)

messenger/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import FormView

from .models import Profile
from .forms import RegisterForm, LoginForm, EditUserNames, EditUserPhoto
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User


@login_required()
def main(request):
    context = dict()
    if request.user.is_superuser:
        users = User.objects.exclude(is_superuser=True)
        context['users'] = users
    else:
        user_admin = User.objects.get(is_superuser=True)
        room_name = User.objects.get(username=request.user)
        context['user_admin'] = user_admin
        context['room_name'] = room_name

    context['page'] = 1
    context['page_title'] = 'Контакты'
    return render(request, 'pwaMessenger/contacts.html', context)


@login_required()
def settings(request):
    context = {
        'page': 3,
        'page_title': 'Настройки',
    }
    return render(request, 'accounts/settings.html', context)


@permission_required('polls.can_vote')
def user_management(request):
    users = User.objects.exclude(is_superuser=True)
    context = {
        'page': 3,
        'page_title': 'Удаление пользователей',
        'users': users,
    }
    return render(request, 'accounts/user_management.html', context)


@login_required()
def personal_settings(request):
    current_user = Profile.objects.get(user__username=request.user)
    context = {
        'page': 3,
        'page_title': 'Профиль',
        'current_user': current_user,
    }
    return render(request, 'accounts/personal_settings.html', context)


@permission_required('polls.can_vote')
def delete_user(request, user_id):
    user = User.objects.get(id=user_id)
    user.delete()
    return HttpResponseRedirect(reverse('accounts:user_management'))


class EditNamesView(LoginRequiredMixin, FormView):
    form_class = EditUserNames
    page_title = 'Настройки'
    template_name = 'accounts/edit_user_names.html'

    def get_context_data(self, **kwargs):
        context = super(EditNamesView, self).get_context_data(**kwargs)
        context['page'] = 3
        context['page_title'] = 'Профиль'
        return context

    def get(self, request):
        form = EditUserNames()

        return super(EditNamesView, self).get(request, form=form)

    def post(self, request, *args, **kwargs):
        form = EditUserNames(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            current_user = User.objects.get(username=request.user)
            current_user.first_name = data['first_name']
            current_user.last_name = data['last_name']
            current_user.save()
            return HttpResponseRedirect(reverse('accounts:settings'))

        return super(EditNamesView, self).get(request, form=form)


@login_required()
def edit_user_img(request):
    data = Profile.objects.get(user__username=request.user)
    form = EditUserPhoto(instance=data)
    if request.POST:
        data = Profile.objects.get(user__username=request.user)
        form = EditUserPhoto(request.POST, request.FILES, instance=data)
        if form.is_valid():
            image = form.save(commit=False)
            image.user_id = request.user
            image.save()
            return HttpResponseRedirect(reverse('accounts:settings'))
    context = {
        'form': form,
        'page_title': 'Профиль',
    }
    return render(request, "accounts/edit_user_img.html", context)


# class EditUserImg(LoginRequiredMixin, FormView):
#     form_class = EditUserPhoto
#     page_title = 'Настройки'
#     template_name = 'accounts/edit_user_img.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(EditUserImg, self).get_context_data(**kwargs)
#         context['page'] = 3
#         context['page_title'] = 'Личные настройки'
#         return context
#
#     def get(self, request):
#         form = EditUserImg()
#         return super(EditUserImg, self).get(request, form=form)
#
#     def post(self, request, *args, **kwargs):
#         form = EditUserImg(request.POST)
#
#         if form.is_valid():
#             current_user = Profile.objects.get(user__username=request.user)
#             photo = request.FILES['photo']
#             current_user.photo = photo
#             current_user.save()
#             return HttpResponseRedirect(reverse('accounts:settings'))
#
#         return super(EditUserImg, self).get(request, form=form)


# def edit_user_img(request):
#     form = EditUserPhoto()
#     if request.method == 'POST':
#         form = EditUserPhoto(request.POST, request.FILES)
#         if form.is_valid():
#             if 'photo' in request.FILES:
#                 form.photo = request.FILES['photo']
#             form.save(commit=True)
#             return HttpResponseRedirect(reverse('accounts:settings'))
#         else:
#             print(form.errors)
#         context = {
#             'form': form,
#             'page_title': 'Настройки',
#         }
#         return render(request, 'accounts/add_simple_flower.html', context)


class RegisterView(PermissionRequiredMixin, FormView):
    permission_required = 'polls.can_vote'

    form_class = RegisterForm
    page_title = 'Register'
    template_name = 'accounts/register.html'

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['page'] = 3
        context['page_title'] = 'Создать пользователя'
        return context

    def get(self, request):
        form = RegisterForm()

        return super(RegisterView, self).get(request, form=form)

    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            new_profile = User.objects.create_user(
                username=data['username'],
                password=data['password'],
            )
            if new_profile:
                return HttpResponseRedirect(reverse('accounts:settings'))

        return super(RegisterView, self).get(request, form=form)


class LoginView(FormView):
    form_class = LoginForm
    page_title = 'Login'
    template_name = 'accounts/login.html'

    def get(self, request):
        form = LoginForm()
        return super(LoginView, self).get(request, form=form)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('Chat:chat_choice'))

        return super(LoginView, self).get(request, form=form)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))

messenger/accounts/templates/accounts/edit.html
{% extends "pwaMessenger/main.html" %}

{% block title %}Edit your account{% endblock %}

{% block main %}
    <h1>Edit your account</h1>
    <p>You can edit your account using the following form:</p>
    <form action="." method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save changes"></p>
    </form>
{% endblock %}

messenger/accounts/templates/accounts/edit_user_img.html
{% extends 'pwaMessenger/main.html' %}
{% block title %}{{page_title}}{% endblock title %}
{% block main %}

<div class="col-12 p-3">
    <form class="md-form" method='POST' action="{% url 'accounts:edit_user_img' %}" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="file-field">
            <div class="btn default-color-dark btn-sm float-left">
                <span class="savemepls"><i class="fas fa-upload mr-2" aria-hidden="true"></i>Выберите фото</span>
                {{ form.photo }}
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate text-white" type="text" placeholder="Ваше фото">
            </div>
        </div>
        <div class="form-row mt-4">
            <button class="btn btn-default btn-block btn-sm" type="submit">Сохранить</button>
        </div>
    </form>

</div>
{% endblock main %}
{% block scripts %}
<script>
    $(document).ready(function () {
        $('.btn.default-color-dark.btn-sm.float-left.waves-effect.waves-light').children().not('.savemepls').not('#id_photo').remove();
    })
    var text = $('.btn.default-color-dark.btn-sm.float-left.waves-effect.waves-light').html();
    text = text.replace('На данный момент:', '');
    text = text.replace('Изменить:', '');
    $('.btn.default-color-dark.btn-sm.float-left.waves-effect.waves-light').html(text);
</script>
{% endblock scripts %}

messenger/accounts/templates/accounts/edit_user_names.html
{% extends 'pwaMessenger/main.html' %}
{% block title %}{{page_title}}{% endblock title %}
{% block main %}

<div class="col-12 p-3">
    <form method='POST' action="{% url 'accounts:edit_user_names' %}">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3 md-form">
                <label for="loginInput" class="text-white">Имя</label>
               {{ form.first_name }}
                <div class="valid-feedback">
                    Подходит
                </div>
            </div>
            <div class="col-md-4 mb-3 md-form">
                <label for="passwordInput" class="text-white">Фамилия</label>
                {{ form.last_name }}
                <div class="valid-feedback">
                    Подходит
                </div>
            </div>

        </div>
        <div class="from-row mt-4">
            <button class="btn btn-default btn-block btn-sm" type="submit">Сохранить</button>
        </div>
    </form>
</div>


{% endblock main %}

messenger/accounts/templates/accounts/login.html
{% extends 'pwaMessenger/main.html' %}
{% block title %}{{page_title}}{% endblock title %}
{% block login %}
<main class="overflow-auto">
    <div class="container">
        <div class="row my-5 py-3 text-white">
            <div class="col-12 d-flex justify-content-center">
                <img src="images/manifest/icon-72x72.png" alt="">
            </div>
            <div class="col-12 p-3">
                <form method='POST' action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    {% if form.username.errors %}{% endif %}
                    <div class="form-row">
                        <div class="col-md-4 mb-3 md-form">
                            <label for="loginInput" class="text-white">Логин</label>
                            {{ form.username }}
                            {% if form.username.errors %}
                            {{ form.username.errors }}
                            {% endif %}
                        </div>
                        <div class="col-md-4 mb-3 md-form">
                            <label for="passwordInput" class="text-white">Пароль</label>
                            {{ form.password }}
                            {% if form.password.errors %}
                            {{ form.password.errors }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="from-row mt-4">
                        <button class="btn btn-default btn-block btn-sm" type="submit">Войти</button>
                    </div>
                </form>
            </div>


        </div>
    </div>
    <!--</main>-->
    <!--<div class="container vh-100">-->

    <!--    <div class="row h-100 align-items-center px-4 py-5">-->
    <!--        <div class="col-12">-->
    <!--            <h1 class="logo text-center">Логотип</h1>-->
    <!--        </div>-->
    <!--        <div class="col-12">-->
    <!--            <form method='POST' action="{% url 'accounts:login' %}">-->
    <!--                {% csrf_token %}-->
    <!--                {% if form.username.errors %}{% endif %}-->
    <!--                <div class="form-group">-->
    <!--                    <label for="loginInput">Логин</label>-->
    <!--                    &lt;!&ndash;                    <input type="text" class="form-control form-login" id="loginInput" required>&ndash;&gt;-->
    <!--                    {{ form.username }}-->
    <!--                    {% if form.username.errors %}-->
    <!--                    {{ form.username.errors }}-->
    <!--                    {% endif %}-->
    <!--                </div>-->
    <!--                <div class="form-group">-->
    <!--                    <label for="passwordInput">Пароль</label>-->
    <!--                    &lt;!&ndash;                    <input type="password" class="form-control form-login" id="passwordInput" required>&ndash;&gt;-->
    <!--                    {{ form.password }}-->
    <!--                    {% if form.password.errors %}-->
    <!--                    {{ form.password.errors }}-->
    <!--                    {% endif %}-->
    <!--                </div>-->
    <!--                <button type="submit" class="btn btn-main btn-login">Войти</button>-->
    <!--            </form>-->
    <!--        </div>-->
    <!--    </div>-->
    <!--</div>-->
    {% endblock login %}

messenger/accounts/templates/accounts/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Main{% endblock title %}</title>
    <style>
        main {
            width: 40%;
        }

        input {
            display: block;
            padding: 10px;
            margin: 5px;
            width: 100%;
        }

        button {
            display: block;
            padding: 10px;
            margin: 5px;
            width: 100%;
        }

        a {
            padding: 5px;
        }

        div {
            display: flex;
            background-color: black;
        }

        div a {
            color: white;
            border: white solid 1px;
            text-decoration: none;
        }

        .root {
            background-color: black;
        }

        .user {
            background-color: green;
        }
    </style>
</head>
<body>

<div>
    <a class="root" href="{% url 'accounts:main' %}">main</a>
    <a class="user" href="{% url 'accounts:logout' %}">logout</a>
    <a class="user" href="{% url 'accounts:login' %}">login</a>
    <a class="root" href="{% url 'accounts:register' %}">register</a>
    <a class="user" href="{% url 'accounts:settings' %}">settings</a>
    <a class="root" href="{% url 'accounts:user_management' %}">user_management</a>
    <a class="user" href="{% url 'accounts:personal_settings' %}">personal_settings</a>
</div>
<main>

    <br>
    <br>
    {% block body %}
    current_user = {{ current_user }}<br>
    first_name = {{ current_user.first_name }}<br>
    last_name email = {{ current_user.last_name }}<br>
    password = {{ current_user.password }}<br>
    groups = {{ current_user.groups }}<br>
    user_permissions = {{ current_user.user_permissions }}<br>
    is_staff = {{ current_user.is_staff }}<br>
    is_active = {{ current_user.is_active }}<br>
    is_superuser = {{ current_user.is_superuser }}<br>
    last_login = {{ current_user.last_login }}<br>
    date_joined = {{ current_user.date_joined }}<br>
    <hr>
    {% for user in all_users %}
    user = {{ user }}<br>
    {% endfor %}
    {% endblock body %}

</main>
</body>
</html>

messenger/accounts/templates/accounts/personal_settings.html
{% extends 'pwaMessenger/main.html' %}
{% block nav %}
<li class="nav-item">
    <a class="nav-link p-0" href="{% url 'accounts:settings' %}">
        <svg fill="#FFFFFF" height="36" viewBox="0 0 24 24" width="36" xmlns="http://www.w3.org/2000/svg">
            <path d="M15.41 16.09l-4.58-4.59 4.58-4.59L14 5.5l-6 6 6 6z"/>
            <path d="M0-.5h24v24H0z" fill="none"/>
        </svg>
    </a>
</li>
{% endblock nav %}
{% block title %}{{page_title}}{% endblock title %}
{% block main %}
<div class="col-12 mt-3">
    <div class="row">
        <div class="col-12 d-flex align-items-center">
            <h1 class="text-left h4-responsive text-capitalize">{{ current_user.user }}</h1>
        </div>
    </div>
</div>
<div class="col-12 mt-3">
    <div class="row">
        <div class="col-9 d-flex align-items-center">
            <h1 class="text-left h4-responsive text-capitalize">
                {% if current_user.user.first_name or current_user.user.last_name %}
                {{ current_user.user.first_name }} {{ current_user.user.last_name }}
                {% else %}
                Нет имени и фамилии
                {% endif %}
            </h1>
        </div>
        <div class="col-3 d-flex align-items-center">
            <a href="{% url 'accounts:edit_user_names' %}" class="btn btn-default btn-block text-center p-3"><i
                    class="fas fa-user-edit"></i></a>
        </div>
    </div>
</div>
<div class="col-12 mt-3">
    <div class="row">
        <div class="col-9 d-flex align-items-center">
            <img src="/media/{{ current_user.photo }}" class="user-photo elegant-color-dark rounded float-left" alt="">
        </div>
        <div class="col-3 d-flex align-items-center">
            <a href="{% url 'accounts:edit_user_img' %}" class="btn btn-default btn-block text-center p-3"><i
                    class="fas fa-user-edit"></i></a>
        </div>
    </div>
</div>

{% endblock %}

messenger/accounts/templates/accounts/register.html
{% extends 'pwaMessenger/main.html' %}
{% block nav %}
<li class="nav-item">
    <a class="nav-link p-0" href="{% url 'accounts:settings' %}">
        <svg fill="#FFFFFF" height="36" viewBox="0 0 24 24" width="36" xmlns="http://www.w3.org/2000/svg">
            <path d="M15.41 16.09l-4.58-4.59 4.58-4.59L14 5.5l-6 6 6 6z"/>
            <path d="M0-.5h24v24H0z" fill="none"/>
        </svg>
    </a>
</li>
{% endblock nav %}
{% block title %}{{page_title}}{% endblock title %}
{% block main %}
<div class="col-12 p-3">
    <form method='POST' action="{% url 'accounts:register' %}">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3 md-form">
                <label for="loginInput" class="text-white">Логин</label>
                {{ form.username }}
                {% if form.username.errors %}
                {{ form.username.errors }}
                {% endif %}
            </div>
            <div class="col-md-4 mb-3 md-form">
                <label for="passwordInput" class="text-white">Пароль</label>
                {{ form.password }}
                {% if form.password.errors %}
                {{ form.password.errors }}
                {% endif %}
            </div>
            <div class="col-md-4 mb-3 md-form">
                <label for="passwordInput" class="text-white">Пароль ещё раз</label>
                {{ form.password2 }}
                {% if form.password.errors %}
                {{ form.password.errors }}
                {% endif %}
            </div>
        </div>
        <div class="from-row mt-4">
            <button class="btn btn-default btn-block btn-sm" type="submit">Создать</button>
        </div>
    </form>
</div>
{% endblock main %}

messenger/accounts/templates/accounts/settings.html
{% extends 'pwaMessenger/main.html' %}
{% block title %}{{page_title}}{% endblock title %}
{% block main %}
{% if request.user.is_superuser %}
<div class="col-12 p-0 pt-3">
    <div class="btn-group w-100 dropleft">
        <a href="{% url 'accounts:register' %}" class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <p class="text-left h4-responsive text-capitalize ml-2"><i class="fas fa-user-plus"></i> Создать
                пользователя</p>
        </a>
    </div>
</div>
<div class="col-12 p-0 pt-3">
    <div class="btn-group w-100 dropleft">
        <a href="{% url 'accounts:user_management' %}" class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <p class="text-left h4-responsive text-capitalize ml-2"><i class="fas fa-user-minus"></i>
                Удалить пользователя</p>
        </a>
    </div>
</div>
{% endif %}
<div class="col-12 p-0 pt-3">
    <div class="btn-group w-100 dropleft">
        <a href="{% url 'accounts:personal_settings' %}" class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <p class="text-left h4-responsive text-capitalize ml-2"><i class="fas fa-user-cog"></i>
                Профиль</p>
        </a>
    </div>
</div>
<div class="col-12 p-0 pt-5">
    <div class="btn-group w-100 dropleft">
        <a href="{% url 'accounts:logout' %}" class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <p class="text-left h4-responsive text-capitalize ml-2"><i class="fas fa-sign-out-alt"></i>
                Выход</p>
        </a>
    </div>
</div>
{% endblock %}

messenger/accounts/templates/accounts/user_management.html
{% extends 'pwaMessenger/main.html' %}
{% block nav %}
<li class="nav-item">
    <a class="nav-link p-0" href="{% url 'accounts:settings' %}">
        <svg fill="#FFFFFF" height="36" viewBox="0 0 24 24" width="36" xmlns="http://www.w3.org/2000/svg">
            <path d="M15.41 16.09l-4.58-4.59 4.58-4.59L14 5.5l-6 6 6 6z"/>
            <path d="M0-.5h24v24H0z" fill="none"/>
        </svg>
    </a>
</li>
{% endblock nav %}
{% block title %}{{page_title}}{% endblock title %}
{% block main %}
{% for user in users %}
<div class="col-12 p-0 pt-1">
    <div class="btn-group w-100 dropleft">
        <a class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <img src="/media/{{ user.profile.photo }}" class="user-photo elegant-color-dark rounded float-left" alt="">
            {% if user.first_name != '' and user.last_name != ''%}
            <p class="text-left h4-responsive text-capitalize ml-2">
                {{ user.first_name}} {{ user.last_name}} ({{user}})
            </p>
            {% else %}
            <p class="text-left h4-responsive text-capitalize ml-2">{{ user }}</p>
            {% endif %}
        </a>
        <a href="{% url 'accounts:delete_user' user.id %}" class="btn btn-danger p-4"><i class="fas fa-user-minus"></i></a>
    </div>
</div>
{% endfor %}
{% endblock %}