messenger/ChatApp/urls.py
from django.urls import path

from . import views


app_name = 'Chat'
urlpatterns = [
    path('chat_choice/', views.chat_choice, name='chat_choice'),
    path('distribution/', views.distribution, name='distribution'),
    path('save_distribution/', views.save_distribution, name='save_distribution'),
    path('delete_room/<str:room_name>', views.delete_room, name='delete_room'),
    path('<str:room_name>/', views.room, name='room'),
]

messenger/accounts/urls.py
from django.urls import path
from .views import \
    RegisterView, LoginView, logout_view, \
    main, settings, user_management, \
    personal_settings, EditNamesView, delete_user, edit_user_img

#Изменения: убрал contacts из импорта


app_name = 'accounts'
urlpatterns = [
    path('', main, name='main'),
    path('settings/', settings, name='settings'),
    path('user_management/', user_management, name='user_management'),
    # path('edit/', edit, name='edit'),
    # path('contacts/', contacts, name='contacts'),
    path('personal_settings/', personal_settings, name='personal_settings'),
    path('edit_user_names/', EditNamesView.as_view(), name='edit_user_names'),
    path('edit_user_img/', edit_user_img, name='edit_user_img'),

    path('delete_user/<int:user_id>', delete_user, name='delete_user'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

messenger/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls')),
    path('chat/', include('ChatApp.urls')),
    path('accounts/', include(('accounts.urls'))),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/pwaMessenger/models.py
from django.db import models

# Create your models here.
class Messange(models.Model):
    title = models.TextField()

messenger/pwaMessenger/views.py
from django.shortcuts import render

# Create your views here.

messenger/pwaMessenger/templates/pwaMessenger/contacts.html
{% extends 'pwaMessenger/main.html' %}
{% block title %}{{page_title}}{% endblock title %}
{% block search %}
<button class="navbar-toggler toggler-example" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="dark-blue-text">
                <i class="fas fa-bars fa-1x"></i>
            </span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent1">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <select class="mdb-select md-form dropdown-default" searchable="Поиск">
                <option value="" disabled selected>Выберите контакт</option>
                {% for user in users %}
                {% if user.first_name != '' and user.last_name != ''%}
                <option data-url="{% url 'Chat:room' user %}">{{ user.first_name}} {{ user.last_name}} ({{user}})
                </option>
                {% else %}
                <option data-url="{% url 'Chat:room' user %}">{{user}}</option>
                {% endif %}

                {% endfor %}
            </select>
        </li>
        <li class="nav-item">
            <label class="mdb-main-label">Выберите контакт</label>
        </li>
        <li class="nav-item d-flex justify-content-center">
            <a href="{% url 'Chat:distribution' %}" class="mdb-main-label btn btn-default">Групповая рассылка</a>
        </li>
    </ul>
</div>
{% endblock search %}
{% block main %}
{% if request.user.is_superuser %}
{% for user in users %}
<div class="col-12 p-0 pt-1">
    <div class="btn-group w-100 dropleft">
        <a href="{% url 'Chat:room' user %}" class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <img src="media/{{ user.profile.photo  }}" class="user-photo elegant-color-dark rounded float-left" alt="">
            {% if user.first_name != '' and user.last_name != ''%}
            <p class="text-left h4-responsive text-capitalize ml-2">{{ user.first_name}} {{ user.last_name}}</p>
            {% else %}
            <p class="text-left h4-responsive text-capitalize ml-2">{{ user}}</p>
            {% endif %}
        </a>
    </div>
</div>
{% endfor %}
{% else %}
<div class="col-12 p-0 pt-1">
    <div class="btn-group w-100 dropleft">
        <a href="{% url 'Chat:room' room_name %}" class="btn elegant-color w-100 p-2 d-flex align-items-center">
            <img src="/media/{{ user_admin.profile.photo  }}" class="user-photo elegant-color-dark rounded float-left" alt="">
            {% if user_admin.first_name != '' and user_admin.last_name != ''%}
            <p class="text-left h4-responsive text-capitalize ml-2">{{ user_admin.first_name}} {{ user_admin.last_name}}</p>
            {% else %}
            <p class="text-left h4-responsive text-capitalize ml-2">{{ user_admin }}</p>
            {% endif %}
        </a>
    </div>
</div>
{% endif %}
{% endblock main %}
{% block scripts %}
<!--  Адаптивный поиск  -->
<script>
    //Переход по результату
    $(".mdb-select").change(function () {
        let option = $(this).find('option:selected');
        if (option.data("url")) {
            window.location.href = option.data("url");
        }
    });
</script>
{% endblock %}

messenger/pwaMessenger/templates/pwaMessenger/main.html
{% load static %}
<!doctype html>
<html lang="ru">


<head>
    <meta charset="utf-8">
    <title>Griffin</title>
    <!--    PWA -->
    <meta name="generator" content="PWA Starter Kit">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, minimum-scale=1, maximum-scale=1">
    <meta name="description" content="Griffin">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!--
        The `<base>` tag below is present to support two advanced deployment options:
        1) Differential serving. 2) Serving from a non-root path.

        Instead of manually editing the `<base>` tag yourself, you should generally either:
        a) Add a `basePath` property to the build configuration in your `polymer.json`.
        b) Use the `--base-path` command-line option for `polymer build`.
      -->
    <!--    <base href="/">-->

    <link rel="icon" href="{% static 'pwaMessenger/images/favicon.ico' %}">

    <!-- See https://goo.gl/OOhYW5 -->
    <link rel="manifest" href="{% static 'pwaMessenger/manifest.json' %}">

    <!-- See https://goo.gl/qRE0vM -->
    <meta name="theme-color" content="#000000">

    <!-- Add to homescreen for Chrome on Android. Fallback for manifest.json -->
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Griffin">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="apple-mobile-web-app-title" content="Griffin">

    <!-- Homescreen icons -->
    <link rel="apple-touch-icon" href="{% static 'pwaMessenger/images/manifest/icon-48x48.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'pwaMessenger/images/manifest/icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="96x96" href="{% static 'pwaMessenger/images/manifest/icon-96x96.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'pwaMessenger/images/manifest/icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="192x192" href="{% static 'pwaMessenger/images/manifest/icon-192x192.png' %}">

    <!-- Tile icon for Windows 8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="{% static 'pwaMessenger/images/manifest/icon-144x144.png' %}">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="msapplication-tap-highlight" content="no">

    <!-- Performance tip: hint to the browser to start the handshake for the fonts site -->
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <script>
        // Load and register pre-caching Service Worker
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', function () {
                navigator.serviceWorker.register("{% static 'pwaMessenger/service-worker.js' %}", {
                    scope: '/',
                });
            });
        }

        // Redux assumes `process.env.NODE_ENV` exists in the ES module build.
        // https://github.com/reactjs/redux/issues/2907
        window.process = {env: {NODE_ENV: 'production'}};
    </script>
    <!--    /PWA -->

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'pwaMessenger/font/css/all.css' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'pwaMessenger/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'pwaMessenger/css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'pwaMessenger/css/style.css' %}" rel="stylesheet">
</head>

<body>
<div id="mdb-preloader" class="flex-center">
    <div class="preloader-wrapper active">
        <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div>
            <div class="gap-patch">
                <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
</div>
{% block login %}
<header>

    <nav class="navbar fixed-top navbar-dark elegant-color-dark scrolling-navbar">

        <ul class="navbar-nav nav-flex-icons">
            {% block nav %}
            {% endblock nav %}
            <li class="nav-item d-flex align-items-center">
                <h1 class="navbar-brand text-center" href="#">
                    <strong>{% block title %}{{page_title}}{% endblock title%}</strong>
                </h1>
            </li>

        </ul>
        {% block search %}

        {% endblock search %}
    </nav>

</header>
<main class="overflow-auto">
    <div class="container">
        <div class="row my-5 py-3 text-white">

            {% block main %}

            {% endblock main %}

        </div>
    </div>
</main>
{% block footer %}
<footer class="page-footer font-small elegant-color-dark fixed-bottom">
    <div class="footer-copyright d-flex justify-content-between py-3">
        <div class="container">
            <div class="row text-center">
                <a href="{% url 'accounts:main' %}" class="col h4 mb-0">
                    <i class="preloader fas fa-address-book {% if page == 1 %}active-menu{% endif %}"></i>
                </a>
                <a href="{% url 'Chat:chat_choice' %}" class="col h4 mb-0">
                    <i class="preloader fas fa-comments {% if page == 2 %}active-menu{% endif %}"></i>
                </a>
                <a href="{% url 'accounts:settings' %}" class="col h4 mb-0">
                    <i class="preloader fas fa-user-cog {% if page == 3 %}active-menu{% endif %}"></i>
                </a>
            </div>
        </div>
    </div>
</footer>
{% endblock footer %}
{% endblock login %}


<script type="text/javascript" src="{% static 'pwaMessenger/js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'pwaMessenger/js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'pwaMessenger/js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'pwaMessenger/js/mdb.min.js' %}"></script>
<!-- Service-worker-->
<script src="{% static 'pwaMessenger/jquery.ellipsis.min.js' %}"></script>
<!--<script src="{% static 'pwaMessenger/register-worker.js' %}"></script>-->

<script>
    // MSelect
    $(document).ready(function () {
        $('.mdb-select').materialSelect();
    });

</script>
<script>
    // Preloader
    $(window).on('load', function () {
        $('#mdb-preloader').addClass('loaded');
        window.setTimeout(function () {
        }, 1200);
    });
    $('.preloader').on('click', function () {
        $('#mdb-preloader').removeClass('loaded');
        window.setTimeout(function () {
        }, 1200);
    });
</script>
{% block scripts %}

{% endblock scripts %}
</body>

</html>